apiVersion: constraints.gatekeeper.sh/v1beta1
kind: HydraRequiredLimits
metadata:
  name: hydra-containers-must-have-limits
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet", "DaemonSet"]
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaceSelector:
      matchLabels:
        hydra.ccu/managed: "true"
